name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Usa la versión de Node.js que prefieras
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install
        
#      - name: Run tests
#        run: npm test # Opcional: quita esta línea si no tienes pruebas definidas

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
